### PR TITLE
Author Url addition

### PR DESCRIPTION
**Pull request by quorn23**
Adds the ability to use a label 
`"org.hotio.pullio.author.url=` to have the Author name be a link to a change-log, or such.

### CODE REVIEW

**Comment by austinwbest** [comment]
```
pullio_update_url=link
pullio_update_label=text
```

or

```
pullio_update_url={link: url, label: text}
```

Maybe one of those so the link can have a label also specified by the user

**Comment by quorn23** [comment]
> 
> 
> ```
> pullio_update_url=link
> pullio_update_label=text
> ```
> 
> or
> 
> ```
> pullio_update_url={link: url, label: text}
> ```

Changed it to suit the naming better.
The author_url is already an existing field for discord embeds, i opted for just adding an already existing method, this way the request won't change the given layout of the messages. The variable you mention with label is already used by the image name. 

My bash skills are obvs rather basic, so i didn't wanted to over-complicate things, but if there is a more suitable way, i'm always keen to learn :)

**Comment by austinwbest** [comment]
> > ```
> > pullio_update_url=link
> > pullio_update_label=text
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```
> > pullio_update_url={link: url, label: text}
> > ```
> 
> Changed it to suit the naming better. The author_url is already an existing field for discord embeds, i opted for just adding an already existing method, this way the request won't change the given layout of the messages. The variable you mention with label is already used by the image name.
> 
> My bash skills are obvs rather basic, so i didn't wanted to over-complicate things, but if there is a more suitable way, i'm always keen to learn :)

Its no biggie to me, i was only going by the use case of the original request. A way to have a changelog link in the notification with a user defined label for the link. 

Your scenario has only one option, to be used as the author link (predefined discord embed only)

Their way just makes it so it can be used anywhere in any situation (webhook)

As it is a webhook they are after, i can easily not use it as a forced author link but dont have a user defined label to use for it so it would be a use what i call it kinda thing or i have to make something else up (either of those are fine by me). Once hotio weighs in on what he thinks then i can make it work on my end without waiting for it to be committed, etc

**Comment by quorn23** [comment]
Yes, as most of the pullio user (from observation) use the discord hook, i stayed within the definitions of discord [https://discordjs.guide/popular-topics/embeds.html#embed-preview](https://discordjs.guide/popular-topics/embeds.html#embed-preview) to keep it simple and adaptable to any kind of link a user might require.
We're more free with webhooks, compared to discord embeds, as the initial request was regarding discord notification i think this is the easiest way to keep simplicity. As our quick chat, i'm confident you are able to define it gratefully for Notifiarr. ;)

**Comment by austinwbest** [comment]
> Yes, as most of the pullio user (from observation) use the discord hook, i stayed within the definitions of discord https://discordjs.guide/popular-topics/embeds.html#embed-preview to keep it simple and adaptable to any kind of link a user might require. We're more free with webhooks, compared to discord embeds, as the initial request was regarding discord notification i think this is the easiest way to keep simplicity. As our quick chat, i'm confident you are able to define it gratefully for Notifiarr. ;)

Sounds good, i pushed the update to support the new `url` field.

**Comment by mrhotio** [comment]
Can I merge?

**Comment by quorn23** [comment]
> Can I merge?

It's tested with Discord and generic webhooks and Austin handles the addition for Notifarr, so we're good to go from my side

**Pull request merged**
